### PR TITLE
Fix for issue #75

### LINKED ISSUE #75: MAStringReader>>visitNumberDescription broken
This method calls NumberParser class>>isNumber: which in turn calls class side methods that are not implemented on NumberParser in GemStone (yet they are implemented on Pharo).

Observed with:
  GemStone 3.2.6 (64bit)
  Seaside 3.1.4
  Magritte 3.3.1, 3.3.2, 3.5

### PR DESCRIPTION
**Pull request by IwanVosloo**
Changed NumberParser class methods to be able to be used as if NumberParser were a concrete class, using a defaultParserClass (fixes #75)

### CODE REVIEW

**Comment by dalehenrich** [comment]
@IwanVosloo it turns out that the [failed test](https://travis-ci.org/GsDevKit/GsDevKit/jobs/80412331) is due to an unrelated GemStone error that pops up while loading the code into GemStone:

```
ERROR 2734 , a RepositoryError occurred (error 2734), Too many sessions logged in to run with requested number of sessions (RepositoryError)
topaz > exec iferr 1 : stk 
==> 1 RepositoryError (AbstractException) >> _signalFromPrimitive: @5 line 15
2 Repository >> _scanPomWithMaxThreads:waitForLock:pageBufSize:percentCpuActiveLimit:identSet:limit:scanKind:toDirectory: @1 line 1
3 [] in  ExecBlock1 (Repository) >> listInstances:limit:toDirectory:withMaxThreads:maxCpuUsage:memoryOnly: @2 line 19
4 Repository >> _doListInstancesFrom:with:includeMemory: @6 line 7
5 Repository >> listInstances:limit:toDirectory:withMaxThreads:maxCpuUsage:memoryOnly: @19 line 28
6 Repository >> listInstances:limit:toDirectory:withMaxThreads:maxCpuUsage: @2 line 4
7 MCPlatformSupport class >> listInstances:     @2 line 4
8 MCPlatformSupport class >> _migrateInstancesWithSubclassesOf: @21 line 19
9 MCPlatformSupport class >> migrateInstancesWithSubclassesOf: @2 line 3
```

This is something that I will have to look into, but your code is not the root cause ...

Also I know it is confusing, but it looks like you've got a checkout of the GsDevKit/GsDevKit code base, but the current master used in glass is still the old repository glassdb/glass ... eventually I will point folks at this repository (and I know the issues are housed here), but there are a lot of details that I need to work out to make a smooth transition for users and I just don't have the time ...

I would be easier for me then if you opened a new pull request against the glassdb/glass repository ... the test may fail again, but like I said that's an issue that I will have to figure out (the os that travis runs does not have cpu affinity turned on and that confuses gemstone a bit ,,, in the multi-threaded commands) ...

**Comment by dalehenrich** [comment]
@IwanVoslooon second thought, you can leave the rest to me ... I can take your Squeak.v3 package and merge it into the glassdb dev branch and then work on getting the test to pass at my leisure ... since it is a GemStone issue at this point ... no need for you to hassle with these other issues

**Comment by dalehenrich** [comment]
Oops I see you've already do it ... great I really appreciate it!


This PR replaced by https://github.com/glassdb/glass/pull/5

**Comment by IwanVosloo** [comment]
Great Dale, it did look like a build process issue that may not by my fault, but I would not want to jump to conclusions...  I created https://github.com/glassdb/glass/pull/5 instead - just before I saw your "on second thought" comment...

**Comment by dalehenrich** [comment]
No your PR is much appreciated:) With the change on the dev branch I will go ahead and merge your pull request as part of the bugfix sweep is getting tests to pass on all platforms

**Pull request closed without merging**
